import { Roboto, Open_Sans } from "next/font/google"; // Import Google Fonts
import "./globals.css";

// Using Google Fonts for Roboto and Open Sans
const roboto = Roboto({
  weight: "400 900", // You can specify the weight range you want
  subsets: ["latin"], // Optional subset like "latin"
  variable: "--font-roboto", // You can create a CSS variable for the font
});

const openSans = Open_Sans({
  weight: "400 700",
  subsets: ["latin"],
  variable: "--font-open-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${openSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
