import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Example for using a custom font (e.g., "CustomFont")
const customFont = localFont({
  src: [
    { path: "/fonts/CustomFont.woff2", weight: "100 900", format: "woff2" },
    { path: "/fonts/CustomFont.woff", weight: "100 900", format: "woff" },
  ],
  variable: "--font-custom", // Set a CSS variable for the custom font
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${customFont.variable} antialiased`}>{children}</body>
    </html>
  );
}
